---
name: Syntax Check, Install & Test

on:
  - pull_request
  - push

jobs:
  Linux:
    name: ${{ matrix.image }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - almalinux:8
          - almalinux:9
          - archlinux:latest
          - debian:11
          - debian:12
          - fedora:38
          - fedora:39
          - quay.io/centos/centos:stream8
          - quay.io/centos/centos:stream9
          - rockylinux:8
          - rockylinux:9
          - ubuntu:20.04
          - ubuntu:22.04
      fail-fast: false
    container:
      image: ${{ matrix.image }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Dependencies (Arch Linux)
        uses: ./.github/actions/dependencies/install/pacman
        with:
          packages: ${{ env.archlinux-dependencies }}
        if: |
          startsWith(matrix.image, 'archlinux:')

      - name: Install Dependencies (AlmaLinux/CentOS/CentOS Stream/Rocky Linux)
        uses: ./.github/actions/dependencies/install/yum
        with:
          dependencies: epel-release
          groups: ${{ env.almalinux-centos-rockylinux-group-dependencies }}
          packages: ${{ env.almalinux-centos-rockylinux-dependencies }}
        if: |
          startsWith(matrix.image, 'almalinux:') ||
          startsWith(matrix.image, 'centos:') ||
          startsWith(matrix.image, 'quay.io/centos/centos:') ||
          startsWith(matrix.image, 'rockylinux:')

      - name: Install Dependencies (Debian/Ubuntu)
        uses: ./.github/actions/dependencies/install/apt-get
        with:
          packages: ${{ env.debian-ubuntu-dependencies }}
        if: |
          startsWith(matrix.image, 'debian:') ||
          startsWith(matrix.image, 'ubuntu:')

      - name: Install Dependencies (Fedora)
        uses: ./.github/actions/dependencies/install/yum
        with:
          groups: ${{ env.fedora-group-dependencies }}
          packages: ${{ env.fedora-dependencies }}
        if: |
          startsWith(matrix.image, 'fedora:')

      - name: Install Perl Modules
        uses: ./.github/actions/dependencies/install/cpanm
        with:
          modules: ${{ env.perl-modules }}

      - name: Check syntax
        env:
          PERL5LIB: lib
        run: |
          for FILE in monitorix monitorix.cgi lib/*.pm
          do
            perl -Mstrict -Mdiagnostics -cw $FILE
          done

      - name: Install `Monitorix`
        uses: ./.github/actions/install

      - name: Test `Monitorix` with `image_format = PNG`
        uses: ./.github/actions/test
        with:
          image_format: PNG
        timeout-minutes: 5

      - name: Test `Monitorix` with `image_format = SVG`
        uses: ./.github/actions/test
        with:
          image_format: SVG
        timeout-minutes: 5

      - name: Tar `Monitorix` artifacts
        run: |
          echo "image_name=$(echo ${{ matrix.image }} | sed 's#[:/]#-#g')" >> \
            $GITHUB_ENV
          tar --create --gzip --verbose --file artifacts.tar.gz \
            /var/lib/monitorix/www \
            monitorix-httpd.log \
            monitorix-test.conf \
            monitorix.log

      - name: Upload `Monitorix` artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.image_name }}
          path: artifacts.tar.gz
          retention-days: 5

  FreeBSD:
    continue-on-error: true
    name: ${{ matrix.box_generic }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        box_generic:
          - freebsd13
          - freebsd14
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Provision VM
        uses: hummeltech/freebsd-vagrant-action@v1.4
        with:
          box: generic/${{ matrix.box_generic }}

      - name: Install Dependencies (FreeBSD)
        uses: ./.github/actions/dependencies/install/pkg
        with:
          packages: ${{ env.freebsd-dependencies }}

      - name: Check syntax
        env:
          PERL5LIB: lib
        run: |
          for FILE in monitorix monitorix.cgi lib/*.pm
          do
            perl -Mstrict -Mdiagnostics -cw $FILE
          done

      - name: Fix FreeBSD install
        run: |
          sed -i.bak 's/^BACKUP = .*/BACKUP = -B .bak/g' Makefile

      - name: Install `Monitorix`
        uses: ./.github/actions/install

      - name: Test `Monitorix` with `image_format = PNG`
        uses: ./.github/actions/test
        with:
          image_format: PNG
        timeout-minutes: 5

      - name: Test `Monitorix` with `image_format = SVG`
        uses: ./.github/actions/test
        with:
          image_format: SVG
        timeout-minutes: 5

      - name: Tar `Monitorix` artifacts
        run: |
          echo "image_name=$(echo ${{ matrix.box_generic }} | sed 's#[:/]#-#g')" >> \
            $GITHUB_ENV
          tar --create --gzip --verbose --file artifacts.tar.gz \
            /var/lib/monitorix/www \
            monitorix-httpd.log \
            monitorix-test.conf \
            monitorix.log
        if: always()

      - name: Upload `Monitorix` artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.image_name }}
          path: artifacts.tar.gz
          retention-days: 5
        if: always()

env:
  archlinux-dependencies: >-
    base-devel
    cpanminus
    rrdtool
  almalinux-centos-rockylinux-group-dependencies: >-
    "Development Tools"
  almalinux-centos-rockylinux-dependencies: >-
    expat-devel
    openssl
    openssl-devel
    perl-App-cpanminus
    rrdtool
    rrdtool-perl
  debian-ubuntu-dependencies: >-
    build-essential
    cpanminus
    curl
    libexpat1-dev
    librrds-perl
    libssl-dev
    openssl
    rrdtool
    zlib1g-dev
  fedora-group-dependencies: >-
    "C Development Tools and Libraries"
    "Development Libraries"
    "Development Tools"
  fedora-dependencies: >-
    expat-devel
    openssl
    openssl-devel
    perl-App-cpanminus
    rrdtool
    rrdtool-perl
  freebsd-dependencies: >-
    p5-CGI
    p5-Config-General
    p5-DBI
    p5-HTTP-Server-Simple
    p5-MIME-Lite
    p5-Net-IP
    p5-ParallelUserAgent
    p5-XML-LibXML
    p5-XML-Simple
    p5-libwww
    perl5
    rrdtool
  perl-modules: >-
    Config::General
    DBI
    Env
    FindBin
    HTTP::Server::Simple
    IO::Socket::SSL
    LWP::UserAgent
    MIME::Lite
    Net::IP
    XML::LibXML
    XML::Simple
